### ISSUE TITLE
Class Database is declared in two places.

### ISSUE THREAD

**Issue by halojoy** [phpLiteAdmin/pla#2]
Issue regarding the onefile version found in this download link:
https://bitbucket.org/phpliteadmin/public/downloads/phpLiteAdmin_v1-9-7.zip
In the **phpliteadmin.php** the Class Database is in two places.
This gives a fatal error.
Can be fixed by removing one Class Database.

First is in: Line number **4342**
Second is in Line number: **5642**

**Comment by crazy4chrissi** [comment]
Yes, right. When building 1.9.7 a had a copy of the Database class file in the class folder which was accidentally included in phpliteadmin.php when building. I will release phpliteadmin 1.9.7.1 soon to fix this.

**Comment by halojoy** [comment]
The github version with many files does not have this issue.
At my server I have tested both possibilities.
Still I love the onefile version. It is so simple to just stick in one single file.
phpLiteAdmin has always  worked well för me.
I love it.
I have created a fork for onefile  pla:  https://github.com/halojoy/onefile-pla

**Comment by crazy4chrissi** [comment]
Yes, the issue comes from my local clone, there has been no problem in the repository.

The onefile version is built automatically from the seperated files in the respository by running the build.php.

We develop in separated files, but we release onefile versions.
I just released 1.9.7.1 which solves this issue.
https://bitbucket.org/phpliteadmin/public/downloads/phpLiteAdmin_v1-9-7-1.zip

Thanks for letting us know. Please tell us if you find any more issues.
